### PR TITLE
Upgrade and improvments

### PR DESCRIPTION
**Pull request by Lezek123**
**_This is a draft PR currently using `@joystream/types 0.13` tarball._**

Some changes are based on issue https://github.com/Joystream/status-endpoint-joystream/issues/12
Implemented changes/improvements so far:
- Upgraded dependencies and did some code cleanup that became possible thanks to new `@polkadot/api` and `@joystream/types` (with `augment-api`)
- Automatic burns now always try to burn the entire balance from burn address and are continously executed if the balance is > 0
- Burns performed by the burning address are parsed in the same way exchanges are. Both of those are now based on extrinsics found in the processed blocks. This means that manual burns will also be included in `burns` array.
- No distinction between `totalIssuance` and `actualIssuance`
- added `logTime` timestamps in some of the db entries
- Fixed `validators.total_stake` (now using new `api.query.staking.erasTotalStake` method)
- Improved `console.log` / `console.error` coverage

### Explaination of some information returned by status server:
- `totalIssuance` - current total JOY issuance queried directly from chain
- `burns` - succesful manual/automatic burns performed by burning address (burn amount equals to transaction tip value)
_This data comes from parsed blocks (which means 10 blocks lag in order to have probablistic finality)_
- `burnAddressBalance` - current burning address balance queried directly from chain
- `executedBurnsAmount` - sum of `burns`
- `exchanges` - successful transfers of balance to burn address, which trigger `sizeDollarPool` reduction
_This data comes from parsed blocks (which means 10 block lag in order to have probablistic finality)_

### Example exchange flow:
```
X = some constant block number
TI = total issuance at block X
```

- `block X`: We send `100` JOY tokens to burning address
- `block X + 1`: our exchange transaction is included in the current block
- `block X + 1`: `burnAddressBalance` returned by the status server is now `100`, as it is queried directly from chain
- `block X + 1/2`: status server sends a transaction to burn `burnAddressBalance` (because it is > 0)
- `block X + 2/3`: burning transaction is included in the current block
- `block X + 2/3`: at this point `burnAddressBalance` is `0` and `executedBurnsAmount` is also `0` (probabilistic finality not yet achieved for burn transaction)
- `block X + 2/3`: in the UI `totalIssuance` drops to `TI-100` but `sizeDollarPool` is not yet affected which means the price now appears slightly higher than it actually will be once this block will be processed (which will happen after 10 more blocks)
- `block X + 11`: Exchange transaction is processed - `exchanges` array is updated and `sizeDollarPool` is reduced. The price in the UI is "back to normal"
- `block X + 12/13`: Burning transaction is processed - `burns` and `executedBurnsAmount` are updated

### CODE REVIEW

**Comment by Lezek123** [comment]
- Added dates to all `console.log`'s and `console.error`'s exposed in `out.log` and `err.log` files (note that those are local time, while dates stored in the database are UTC, so they may differ)
- Added commands to shedule dollar pool increase and change exchange status (which is now part of the `Exchange` entity).
Examples:
```
yarn increasePool 100 # Increase pool by $100 before processing next block
yarn increasePool 200 50000 # Increase pool by $200 before processing block 50000
yarn setExchangeStatus 0 FINALIZED # Finalize first exchange in the array of exchanges
yarn setExchangeStatus 5 FINALIZED # Finalize 6th exchange in the array of exchanges
```

**Comment by Lezek123** [comment]
Implemented dollar pool size change log in `exchanges.json` based on: https://github.com/Joystream/status-endpoint-joystream/issues/12#issuecomment-694827669

**Review by bwhm — CHANGES_REQUESTED** [review]
Very minor changes requested:
1. `poolChangeHistory` not exposed to the status server
2. change the types from the tarball to "^0.13.1"

Some notes:

The version before your latest commit has ran from roughly when the test-testnet was launched, and it has a logged 19344 warnings. For most of the blocks between 30917 and 57764 (not quite 26847 though):

```json
{
  "warnings": [
    {
      "blockNumber": 30917,
      "message": "Processing before finalized! Finalized: 30916, Processing: 30917",
      "logTime": "2020-09-15T13:46:30.962Z"
    },
//...
    {
      "blockNumber": 57764,
      "message": "Processing before finalized! Finalized: 56507, Processing: 57764",
      "logTime": "2020-09-17T11:04:36.904Z"
    }
```

This is almost certainly during the time I had two validators run with the same session keys, so it will likely not happen frequently on the actual network.

I did spin up a "new" one with the recent changes, and built with deployed types "0.13.1". As it was started after the aforementioned range, it hasn't logged a single warning... 

So IMO, it's not worth dealing with, but still wanted to provide feedback :D

Finally, I used the same VPS to host both, with the same `.env` except the port.

The "new" node didn't have any problems with the fact that the exchanges was already burned.
When I made a new transaction, with both running, one of them made the unsurprising entry to `err.log`:
```
RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (390000123 vs 390000123): The transaction has too low priority to replace another transaction already in the pool.
```
...but both of them handled it "well" :D

**Review by bwhm — APPROVED** [review]
Nice :)

**Pull request merged**
